### ISSUE TITLE
[BUG]: updateProperty Controller

### ISSUE THREAD

**Issue by mbvgua** [dwella-org/backend#3]
### Description of the bug

While building the getPropertyBy controller, I realized some bugs in the updateProperty Controller:

-  While updating the property, more and more escape characters were being added to the values within the database. Most likely dues to the JSON.stringify() function within the controller., like so:
![Screenshot from 2024-11-13 09-28-35](https://github.com/user-attachments/assets/b08d1872-29f6-42a6-86fd-81a3b81e9f18)

- In trying to eliminate this abnormally by using the JSON_QUERY() function to properly format JSON, it seemed to append itself on the existing values. Removing the escape characters error and adding a new one.
![Screenshot from 2024-11-13 14-42-45](https://github.com/user-attachments/assets/0b65f9e0-c4b7-407b-a273-605abac839e1)

### Steps To Reproduce

1.Add a new property to the db using the addProperty URL in the collections
2.Try updating it using the updateProperty URL
3.View the updated property by getting a list of all the available properties. As this allows you to compare formatting amongst them

### Additional Information

This has lead me to rethink on the neccessity of using JSON schema  within my database overall.

**Comment by mbugva** [comment]
This was an issue in the SQL Schema stored Procedure. I had used a built in function called JSON_MODIFY() that was adding nested escape characters implicitly. Removing this and instead opting to use a simple stored procedure with basic inputs and instead modifying the strings to be of string type in the application itself resolved this issue:

![Screenshot from 2024-11-15 17-15-34](https://github.com/user-attachments/assets/22ed67f1-a7a7-4044-aa7d-351ef3ada93e)
